server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://senii-db.cpa0reebgby0.ap-northeast-2.rds.amazonaws.com/UdemyServer # 변경해주세요
    username: admin
    password: sehun940412
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    #driver-class-name: com.mysql.jdbc.Driver # mysql 5버전